// Generate .design-sync/ds-styles.css from the real card stylesheet (src/styles.css).
//
// src/styles.css is authored for shadow DOM: the design tokens (--warm, --surface, …) and
// the box-sizing reset live under `:host`. claude.ai/design renders the cards in LIGHT DOM
// (no shadow root), where `:host` never matches — so every `rgb(var(--warm))` would resolve
// to nothing and the cards would render unstyled. This hoists those `:host` rules so the
// tokens land on :root (global) and the reset stays scoped to the card subtrees.
//
// Deterministic: re-run `node .design-sync/gen-styles.mjs` after editing src/styles.css.
// The design-sync build (cfg.cssEntry) consumes the generated file.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const src = readFileSync(join(root, 'src/styles.css'), 'utf8');

// The card root container classes — box-sizing must cover them and their descendants
// (in shadow DOM `:host *` covered the card root because it was a host descendant; in
// light DOM the card root is top-level, so name it explicitly).
const ROOTS = ['.simui-tile', '.simui-graph', '.simui-media', '.simui-chips', '.simui-eflow'];
const boxScope = ROOTS.flatMap((r) => [r, `${r} *`]).join(', ');

const out = src
  // box-sizing reset: scope to the card subtrees (a global `* {}` would leak onto the page)
  .replace(/:host\s*\*\s*\{/, `${boxScope} {`)
  // tokens + geometry custom properties: hoist onto :root so they apply in light DOM;
  // keep :host too for shadow-DOM parity if this CSS is ever loaded inside a shadow root.
  .replace(/:host\s*\{/, ':root, :host {');

// src/styles.css ships exactly two :host rules (the token block + the box-sizing reset).
// More than that means a new :host selector was added that this transform doesn't handle.
const srcHostRules = (src.match(/:host/g) ?? []).length;
if (srcHostRules > 2) {
  console.error(`WARNING: src/styles.css has ${srcHostRules} :host occurrences (expected 2) — a new :host rule may be unconverted.`);
}

const header =
  `/* GENERATED by .design-sync/gen-styles.mjs from src/styles.css — do not edit by hand.\n` +
  `   :host (shadow-DOM) is hoisted to :root so SimUI cards render in claude.ai/design's light DOM.\n` +
  `   Re-run \`node .design-sync/gen-styles.mjs\` after editing src/styles.css. */\n`;

writeFileSync(join(here, 'ds-styles.css'), header + out);
console.log('wrote .design-sync/ds-styles.css');
